import type { Publication } from "./types";

export const publications: Publication[] = [
  {
    id: "medrxiv-fitness-2026",
    title: "Inferring Respiratory Disease Biology from Geolocation Data",
    authors: [
      "Alejandra Rincón Hidalgo",
      "Andrzej K. Jarynowski",
      "Marlli Zambrano",
      "Philip El-Duah",
      "Janik Suer",
      "Ashish Thampi",
      "Richard Pastor",
      "Huynh Thi Phuong",
      "Sten Rüdiger",
      "Stephan Ludwig",
      "Rafael Mikolajczyk",
      "Christian Drosten",
      "Veronika K. Jäger",
      "André Karch",
    ],
    selfIndex: 0,
    role: "first",
    venue: "medRxiv",
    year: 2026,
    doi: "10.64898/2026.03.05.26347578",
    url: "https://doi.org/10.64898/2026.03.05.26347578",
    abstract:
      "We propose an approach that infers biological fitness from mostly non-biological data on infection dynamics and contact levels in a population, applied to SARS-CoV-2 in Germany.",
  },
  {
    id: "epidemics-2026",
    title:
      "Social contact patterns derived from an epidemiological survey and GPS-based co-location data: a systematic comparison using parallel data collections during the COVID-19 pandemic in Germany",
    authors: [
      "Huynh Thi Phuong",
      "Janik Suer",
      "Vitaly Belik",
      "Alejandra Rincón Hidalgo",
      "Andrzej K. Jarynowski",
      "Richard Pastor",
      "Steven Schulz",
      "Ashish Thampi",
      "Chao Xu",
      "Marlli Zambrano",
      "Rafael Mikolajczyk",
      "André Karch",
      "Veronika K. Jaeger",
    ],
    selfIndex: 3,
    role: "co",
    venue: "Epidemics",
    venueDetail: "Vol. 54, 100886",
    year: 2026,
    doi: "10.1016/j.epidem.2026.100886",
    url: "https://doi.org/10.1016/j.epidem.2026.100886",
  },
  {
    id: "medrxiv-abm-2025",
    title:
      "A comparison of random mixing in a structured agent-based model with empirical contact survey data",
    authors: [
      "Janik Suer",
      "Johannes Ponge",
      "Michael Brüggemann",
      "Jan Pablo Burgard",
      "Vitaly Belik",
      "Bernd Hellingrath",
      "Alejandra Rincón Hidalgo",
      "Andrzej K. Jarynowski",
      "Richard Pastor",
      "Huynh Thi Phuong",
      "Steven Schulz",
      "Ashish Thampi",
      "Chao Xu",
      "Marlli Zambrano",
      "Rafael Mikolajczyk",
      "André Karch",
      "Veronika K. Jaeger",
    ],
    selfIndex: 6,
    role: "co",
    venue: "medRxiv",
    year: 2025,
    doi: "10.1101/2025.09.18.25336044",
    url: "https://doi.org/10.1101/2025.09.18.25336044",
  },
  {
    id: "leveraging-realtime-gps-2025",
    title:
      "Leveraging Real-Time Population-Scale GPS Data to Forecast and Identify Components of Epidemic Dynamics",
    authors: ["Alejandra Rincón Hidalgo"],
    selfIndex: 0,
    role: "co",
    venue: "International Journal of Infectious Diseases",
    venueDetail: "Vol. 152, Supplement, March 2025",
    year: 2025,
    url: "https://www.ijidonline.com/",
    abstract:
      "Research on contact networks and Bayesian epidemiological forecasting, revealing Delta and Omicron variants to be 50% and 115% more transmissible than Alpha.",
  },
  {
    id: "berlin-mobility-netmob-2024",
    title: "Urban Segregation and Daily Human Mobility Patterns in Berlin",
    authors: [
      "A. Thampi",
      "M. Zambrano",
      "Alejandra Rincón Hidalgo",
      "A. Jarynowski",
      "V. Belik",
      "S. Schultz",
    ],
    selfIndex: 2,
    role: "co",
    venue: "NetMob 2024",
    venueDetail: "Washington, D.C., October 2024",
    year: 2024,
    url: "https://netmob.org/",
    abstract:
      "Analysis of mobility patterns and urban segregation using crowdsourced GPS data.",
  },
  {
    id: "k3-surfaces-2024",
    title:
      "Non-symplectic automorphisms of order multiple of seven on K3 surfaces",
    authors: [
      "R. Bell",
      "P. Comparin",
      "J. Li",
      "A. Rincón-Hidalgo",
      "A. Sarti",
      "A. Zanardini",
    ],
    selfIndex: 3,
    role: "co",
    venue: "Journal of Pure and Applied Algebra",
    venueDetail: "Vol. 228, Issue 4, 107517",
    year: 2024,
    doi: "10.1016/j.jpaa.2023.107517",
    url: "https://doi.org/10.1016/j.jpaa.2023.107517",
  },
  {
    id: "bridgeland-moduli-2021",
    title: "Moduli of Bridgeland semistable holomorphic triples",
    authors: ["Dominic Bunnett", "Alejandra Rincón-Hidalgo"],
    selfIndex: 1,
    role: "co",
    venue: "arXiv preprint",
    year: 2021,
    arxiv: "2102.04995",
    url: "https://arxiv.org/abs/2102.04995",
    abstract:
      "We prove that the moduli stack of Bridgeland semistable holomorphic triples over a curve of genus at least 1, with a fixed numerical class and phase, is an algebraic stack of finite type over C.",
  },
  {
    id: "bridgeland-stability-2019",
    title:
      "Bridgeland stability conditions on the category of holomorphic triples over curves",
    authors: [
      "Eva Martínez-Romero",
      "Alejandra Rincón-Hidalgo",
      "Arne Rüffer",
    ],
    selfIndex: 1,
    role: "co",
    venue: "arXiv preprint",
    year: 2019,
    arxiv: "1905.04240",
    url: "https://arxiv.org/abs/1905.04240",
    abstract:
      "Complete description of the Bridgeland stability manifold for the bounded derived category of holomorphic triples over a smooth projective curve of genus 1 as a connected, four-dimensional complex manifold.",
  },
];
